service: sls-cron-slack-del-cal
app: sls-cron-slack-del-cal
org: tt151sls

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  profile: 'sls'

# you can overwrite defaults here
#  stage: dev

# you can add statements to the Lambda function's IAM Role here
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "s3:ListBucket"
#          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#        - Effect: "Allow"
#          Action:
#            - "s3:PutObject"
#          Resource:
#            Fn::Join:
#              - ""
#              - - "arn:aws:s3:::"
#                - "Ref" : "ServerlessDeploymentBucket"
#                - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.py'
#    - '!exclude-me-dir/**'
#    - include-me.py
#    - include-me-dir/**

functions:
  noevents:
    handler: handler.noevents

plugins:
  - serverless-python-requirements


custom:
  pythonRequirements:
    dockerizePip: non-linux

configValidationMode: error

